// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MXO9VCFTSaCez7hzgiOh7kXwex8380g',
    appId: '1:850669582744:web:620f8525cf809f960213ed',
    messagingSenderId: '850669582744',
    projectId: 'the-movie-db-c6c51',
    authDomain: 'the-movie-db-c6c51.firebaseapp.com',
    storageBucket: 'the-movie-db-c6c51.appspot.com',
    measurementId: 'G-PL15Y4DXBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlLlcBVDOMAlxm4v_17iQ8D2dMW7uuxc',
    appId: '1:850669582744:android:f5cea1e81f006cfc0213ed',
    messagingSenderId: '850669582744',
    projectId: 'the-movie-db-c6c51',
    storageBucket: 'the-movie-db-c6c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWvRjRFxqBMP0v14f3mpbwdG_BtaS1yo',
    appId: '1:850669582744:ios:790a580dba1744540213ed',
    messagingSenderId: '850669582744',
    projectId: 'the-movie-db-c6c51',
    storageBucket: 'the-movie-db-c6c51.appspot.com',
    iosClientId: '850669582744-f8aod0j9oafgeqh24p4hqq04c0jq7l1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.themoviedbTmdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWvRjRFxqBMP0v14f3mpbwdG_BtaS1yo',
    appId: '1:850669582744:ios:621a8d227a34ab600213ed',
    messagingSenderId: '850669582744',
    projectId: 'the-movie-db-c6c51',
    storageBucket: 'the-movie-db-c6c51.appspot.com',
    iosClientId: '850669582744-gia059anmbr4adrako24hdgpo5v2afdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.themoviedbTmdb.RunnerTests',
  );
}
